CREATE TABLE goods
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR2(50) NOT NULL,
    description VARCHAR2(250),
    price       NUMBER(6,2),

    CONSTRAINT PK_goods PRIMARY KEY (id)
);

CREATE TABLE shops
(
    id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR2(50) NOT NULL,

    CONSTRAINT PK_shops PRIMARY KEY (id)
);

CREATE TABLE warehouses
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR2(50) NOT NULL,

    CONSTRAINT warehouses_pk PRIMARY KEY (id)
);

CREATE TABLE goods_in_stocks
(
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY,
    goods_id           NUMBER NOT NULL,
    warehouse_id       NUMBER NOT NULL,
    available_quantity NUMBER(5) NOT NULL,

    CONSTRAINT PK_goods_in_stocks      PRIMARY KEY (id),
    CONSTRAINT FK_gist_goods           FOREIGN KEY(goods_id) REFERENCES goods(id),
    CONSTRAINT FK_gist_warehouses      FOREIGN KEY(warehouse_id) REFERENCES warehouses(id)
);

CREATE TABLE goods_in_shops
(
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY,
    goods_id           NUMBER NOT NULL,
    shop_id            NUMBER NOT NULL,
    available_quantity NUMBER(5) NOT NULL,

    CONSTRAINT PK_goods_in_shops      PRIMARY KEY (id),
    CONSTRAINT FK_gish_goods          FOREIGN KEY(goods_id) REFERENCES goods(id),
    CONSTRAINT FK_gish_shops          FOREIGN KEY(shop_id) REFERENCES shops(id)
);

CREATE TABLE delivery_requests
(
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    shop_id             NUMBER,
    warehouse_id        NUMBER,
    request_date        DATE NOT NULL,
    arrival_date        DATE NOT NULL,

    CONSTRAINT PK_delivery_requests PRIMARY KEY (id),
    CONSTRAINT FK_dr_shops          FOREIGN KEY(shop_id) REFERENCES shops(id),
    CONSTRAINT FK_dr_warehouses     FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT customer_not_null_ck CHECK ((shop_id is not null and warehouse_id is null)
                                               or (warehouse_id is not null and shop_id is null))
);

CREATE TABLE delivery_request_goods
(
    delivery_request_id NUMBER NOT NULL,
    goods_id NUMBER NOT NULL,

    CONSTRAINT PK_delivery_request_goods PRIMARY KEY (delivery_request_id, goods_id),
    CONSTRAINT FK_drg_delivery_requests  FOREIGN KEY(delivery_request_id) REFERENCES delivery_requests(id),
    CONSTRAINT FK_drg_goods              FOREIGN KEY(goods_id) REFERENCES goods(id)
);

CREATE TABLE delivery_items
(
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    goods_id            NUMBER NOT NULL,
    delivery_request_id NUMBER NOT NULL,
    delivery_status     VARCHAR2(30) NOT NULL,

    CONSTRAINT PK_delivery_items       PRIMARY KEY (id),
    CONSTRAINT FK_di_goods             FOREIGN KEY(goods_id) REFERENCES goods(id),
    CONSTRAINT FK_di_delivery_requests FOREIGN KEY(delivery_request_id) REFERENCES delivery_requests(id)
);
